org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Loom Properties
loom_version=1.13-SNAPSHOT

# Fabric Properties
minecraft_version=1.21.10
loader_version=0.17.3

# Fabric API
fabric_version=0.138.3+1.21.10

# Mod Properties
mod_version=0.0.28-1.21.10
maven_group=net.kyrptonaught
archives_base_name=lemclienthelper

# Dependency Properties
kyrptconfig_version=1.6.1-1.21.4
modmenu_version=16.0.0-rc.1
devlogin_version=3.5
obsidianui_version=0.2.12+mc1.21.6-fabric
midnightlib_version=1.8.3+1.21.9-fabric
midnightcontrols_version=1.11.3-beta.3-fabric
legacy4j_version=1.21.10-1.8.5.2545.5+fabric
factoryapi_version=1.21.10-2.2.6.2545.1+fabric
